import { notFound } from "next/navigation";
import { eq } from "drizzle-orm";
import { shares } from "@/db/schema";
import { getDb } from "@/lib/db";
import { formatCents, formatPercent } from "@/lib/metrics";
import {
  DIMENSION_LABELS,
  formatPercentileAsStanding,
  loadLatestRankings,
  type RankingDimension,
} from "@/lib/rankings";
import { loadDashboardData } from "@/lib/receipts-queries";

type ShareRow = typeof shares.$inferSelect;

type SharePageProps = {
  params: Promise<{ slug: string }>;
};

export const dynamic = "force-dynamic";

type RedactionConfig = {
  projectAliases?: boolean;
  machineNames?: boolean;
  exactCosts?: boolean;
  topSessionNames?: boolean;
  rankingVisible?: boolean;
};

export async function generateMetadata({ params }: SharePageProps) {
  const { slug } = await params;
  return {
    title: `Receipt ${slug}`,
    description: "A metadata-only Claude Code receipt. Generated by Claude's Receipts.",
    openGraph: {
      title: "A Claude Code receipt",
      description: "Metadata-only. Mildly incriminating. Generated by Claude's Receipts.",
    },
  };
}

async function loadShare(slug: string): Promise<ShareRow | null> {
  const db = getDb();
  if (!db) return null;
  const record = await db.query.shares.findFirst({
    where: eq(shares.shareSlug, slug),
  });
  return record ?? null;
}

export default async function PublicSharePage({ params }: SharePageProps) {
  const { slug } = await params;
  const share = await loadShare(slug);
  if (!share) notFound();

  const redaction = (share.redactionConfig ?? {}) as RedactionConfig;
  const liveData = await loadDashboardData(share.userId);
  const rankings = await loadLatestRankings(share.userId);

  const headline = liveData?.overviewStats?.[0]?.value ?? "—";
  const burn = liveData?.overviewStats?.find((s) =>
    s.label.toLowerCase().includes("burn"),
  );
  const highlights = liveData?.highlights ?? [];

  const visibleHighlights = highlights
    .filter((panel) => {
      if (redaction.projectAliases && panel.label === "Highest Burn Project") return false;
      if (redaction.machineNames && panel.label === "Device Mix") return false;
      if (redaction.topSessionNames && panel.label === "This Week's Damage") return false;
      return true;
    })
    .slice(0, 4);

  const rankingEntries: [RankingDimension, number][] = rankings
    ? (Object.entries(rankings) as [RankingDimension, number][])
    : [];
  rankingEntries.sort((a, b) => b[1] - a[1]);
  const topRanking = rankingEntries[0];

  return (
    <main className="receipt-surface">
      <div className="receipt-frame">
        <header className="receipt-header">
          <span className="receipt-kicker">Claude&rsquo;s Receipts</span>
          <h1 className="receipt-title">
            {share.visibility === "public"
              ? "Receipt, published."
              : "Receipt, held privately."}
          </h1>
          <p className="receipt-sub">
            {redaction.exactCosts
              ? "Amounts shown as ranges. Exact figures redacted by the account holder."
              : "All figures metadata-only. No prompts or code contents enter this page."}
          </p>
        </header>

        <section className="receipt-hero">
          <p className="receipt-label">Lifetime damage</p>
          <p className="receipt-hero-value">{headline}</p>
          {burn ? (
            <p className="receipt-hero-note">{burn.value} over the last thirty days</p>
          ) : null}
        </section>

        {visibleHighlights.length ? (
          <section className="receipt-grid">
            {visibleHighlights.map((panel) => (
              <article className="receipt-cell" key={panel.label}>
                <p className="receipt-label">{panel.label}</p>
                <p className="receipt-value">
                  {redaction.exactCosts && panel.value.startsWith("$")
                    ? "$•••"
                    : panel.value}
                </p>
                <p className="receipt-detail">{panel.detail}</p>
              </article>
            ))}
          </section>
        ) : null}

        {redaction.rankingVisible !== false && topRanking ? (
          <section className="receipt-ranking">
            <p className="receipt-label">Internal standing</p>
            <p className="receipt-ranking-line">
              <span className="receipt-ranking-pct">
                {formatPercentileAsStanding(topRanking[1])}
              </span>
              <span className="receipt-ranking-sep">on</span>
              <span className="receipt-ranking-dim">
                {DIMENSION_LABELS[topRanking[0]].toLowerCase()}
              </span>
            </p>
            <ul className="receipt-ranking-list">
              {rankingEntries.slice(1, 4).map(([dim, pct]) => (
                <li key={dim}>
                  <span>{DIMENSION_LABELS[dim]}</span>
                  <span className="receipt-mono">
                    {formatPercentileAsStanding(pct)}
                  </span>
                </li>
              ))}
            </ul>
          </section>
        ) : null}

        <footer className="receipt-footer">
          <span className="receipt-seal">Sealed {share.publishedAt?.toISOString().slice(0, 10) ?? "in draft"}</span>
          <span className="receipt-seal-note">
            Receipt mode &middot; {share.visibility === "public" ? "public link" : "private link"}
          </span>
        </footer>
      </div>
    </main>
  );
}

export { formatCents, formatPercent };
