export const DEFAULT_CATEGORIES = [
    'auto repair shop',
    'auto body shop',
    'tire shop',
    'electrician',
    'plumber',
    'roofer',
    'general contractor',
    'painter',
    'landscaper',
    'flooring store',
    'furniture store',
    'pet store',
    'veterinarian',
    'gym',
    'sporting goods store',
    'hardware store',
    'clothing store',
    'bookstore',
    'bicycle shop',
    'locksmith',
    'moving company',
    'self storage',
    'laundromat',
    'car wash',
    'tattoo shop',
    'photography studio',
    'music store',
    'hunting supply store',
    'farm supply store',
    'snowmobile dealer',
    'ATV dealer',
    'boat dealer',
    'marina',
    'campground',
    'fishing guide',
];

export const EXCLUDED_KEYWORDS = [
    'food truck',
    'lawyer',
    'attorney',
    'law firm',
    'accountant',
    'cpa',
    'tax',
    'financial advisor',
    'insurance',
    'real estate',
    'mortgage',
    'franchise',
    'mcdonald',
    'subway',
    'dunkin',
    'tim horton',
    'starbucks',
    'supercuts',
    'great clips',
    'walmart',
    'target',
    'dollar tree',
    'dollar general',
    'jcpenney',
    'tjmaxx',
    'church',
    'hair salon',
    'nail salon',
    'barbershop',
    'hair studio',
    'beauty salon',
];

export const SOCIAL_PLATFORMS = [
    'facebook.com',
    'instagram.com',
    'twitter.com',
    'x.com',
    'tiktok.com',
    'youtube.com',
    'linkedin.com',
];

export const DEFAULT_TOWNS = [
    'Houlton, Maine',
    'Presque Isle, Maine',
    'Caribou, Maine',
    'Fort Kent, Maine',
    'Millinocket, Maine',
    'Calais, Maine',
    'Machias, Maine',
    'Ellsworth, Maine',
    'Bangor, Maine',
    'Augusta, Maine',
    'Waterville, Maine',
    'Skowhegan, Maine',
    'Dover-Foxcroft, Maine',
    'Rockland, Maine',
    'Belfast, Maine',
    'Eastport, Maine',
    'Lincoln, Maine',
    'Greenville, Maine',
    'Rangeley, Maine',
    'Farmington, Maine',
];

export const NEW_BUSINESS_REVIEW_THRESHOLD = 25;

export const SELECTORS = {
    searchBox: '#searchboxinput',
    resultItem: 'div[role="feed"] > div > div > a',
    scrollContainer: 'div[role="feed"]',
    businessName: 'h1',
    phone: 'button[data-item-id^="phone"]',
    address: 'button[data-item-id="address"]',
    website: 'a[data-item-id="authority"]',
    reviewCount: 'span[aria-label*="review"]',
    rating: 'div[jsaction*="pane.rating"] span[aria-hidden="true"]',
    category: 'button[jsaction*="pane.rating.category"]',
    openingStatus: 'span[aria-label*="open" i], span[aria-label*="closed" i]',
};
