export const DEFAULT_CATEGORIES = [
    'auto repair shop',
    'auto body shop',
    'tire shop',
    'electrician',
    'plumber',
    'roofer',
    'general contractor',
    'painter',
    'landscaper',
    'flooring store',
    'furniture store',
    'pet store',
    'veterinarian',
    'gym',
    'sporting goods store',
    'hardware store',
    'clothing store',
    'bookstore',
    'bicycle shop',
    'locksmith',
    'moving company',
    'self storage',
    'laundromat',
    'car wash',
    'tattoo shop',
    'photography studio',
    'music store',
    'hunting supply store',
    'farm supply store',
    'snowmobile dealer',
    'ATV dealer',
    'boat dealer',
    'marina',
    'campground',
    'fishing guide',
];

export const EXCLUDED_KEYWORDS = [
    // Professional services / not voice-bot fit
    'food truck',
    'lawyer',
    'attorney',
    'law firm',
    'accountant',
    'cpa',
    'financial advisor',
    'insurance',
    'real estate',
    'mortgage',
    'franchise',
    'church',

    // Personal care chains
    'supercuts',
    'great clips',
    'hair salon',
    'nail salon',
    'barbershop',
    'hair studio',
    'beauty salon',

    // Big box / national retail chains
    'walmart',
    'target',
    'dollar tree',
    'dollar general',
    'family dollar',
    'five below',
    'big lots',
    'jcpenney',
    'tjmaxx',
    'marshalls',
    'ross dress',
    'kohl',
    'costco',
    'sams club',
    "sam's club",
    "bj's wholesale",
    'home depot',
    'lowe',
    'menards',
    'ace hardware',
    'true value',
    'tractor supply',
    'best buy',
    'staples',
    'office depot',
    'office max',
    'micro center',
    'gamestop',
    'radioshack',
    'autozone',
    'advance auto',
    "o'reilly auto",
    'napa auto',
    'pep boys',
    'firestone',
    'goodyear',
    'jiffy lube',
    'valvoline',
    'midas',
    'maaco',
    'hobby lobby',
    'michaels',
    'jo-ann',
    'joann fabric',
    "dick's sporting",
    'dicks sporting',
    'academy sports',
    'bass pro',
    'cabela',
    'rei co-op',
    'guitar center',
    'sam ash',
    'petco',
    'petsmart',
    'pet supplies plus',
    'tsc',
    'sherwin-williams',
    'sherwin williams',
    'benjamin moore',
    'ppg paints',
    'ferguson',
    'floor & decor',
    'bed bath',
    'container store',
    'pier 1',
    'crate & barrel',
    'pottery barn',
    'williams sonoma',
    'ikea',
    'at&t store',
    'verizon',
    't-mobile',
    'xfinity',
    'spectrum store',

    // Pharmacy / convenience chains
    'cvs pharmacy',
    'walgreens',
    'rite aid',
    'duane reade',
    '7-eleven',
    'circle k',
    'wawa',
    'sheetz',
    'cumberland farms',
    'irving oil',

    // Grocery chains
    'hannaford',
    'shaw',
    'market basket',
    'stop & shop',
    'stop and shop',
    'price chopper',
    'publix',
    'kroger',
    'safeway',
    'aldi',
    'whole foods',
    'trader joe',
    'wegman',
    'food lion',

    // Fast food / casual dining chains
    'mcdonald',
    'subway',
    'burger king',
    'wendy',
    'kfc',
    'taco bell',
    'pizza hut',
    'dunkin',
    'tim horton',
    'starbucks',
    'domino',
    "papa john",
    'arby',
    'chipotle',
    'panera',
    'jimmy john',
    'jersey mike',
    'firehouse subs',
    'qdoba',
    'five guys',
    'shake shack',
    "chick-fil-a",
    'chick fil a',
    'popeyes',
    'applebee',
    'chili',
    'olive garden',
    'red lobster',
    'outback steakhouse',
    'texas roadhouse',
    'buffalo wild wings',
    'cracker barrel',
    'ihop',
    'denny',
    'waffle house',
    'country kitchen',
    'panda express',
];

export const SOCIAL_PLATFORMS = [
    'facebook.com',
    'instagram.com',
    'twitter.com',
    'x.com',
    'tiktok.com',
    'youtube.com',
    'linkedin.com',
];

export const DEFAULT_TOWNS = [
    'Houlton, Maine',
    'Presque Isle, Maine',
    'Caribou, Maine',
    'Fort Kent, Maine',
    'Millinocket, Maine',
    'Calais, Maine',
    'Machias, Maine',
    'Ellsworth, Maine',
    'Bangor, Maine',
    'Augusta, Maine',
    'Waterville, Maine',
    'Skowhegan, Maine',
    'Dover-Foxcroft, Maine',
    'Rockland, Maine',
    'Belfast, Maine',
    'Eastport, Maine',
    'Lincoln, Maine',
    'Greenville, Maine',
    'Rangeley, Maine',
    'Farmington, Maine',
];

export const NEW_BUSINESS_REVIEW_THRESHOLD = 25;

export const SELECTORS = {
    searchBox: '#searchboxinput',
    resultItem: 'div[role="feed"] > div > div > a',
    scrollContainer: 'div[role="feed"]',
    businessName: 'h1',
    phone: 'button[data-item-id^="phone"]',
    address: 'button[data-item-id="address"]',
    website: 'a[data-item-id="authority"]',
    reviewCount: 'span[aria-label*="review"]',
    rating: 'div[jsaction*="pane.rating"] span[aria-hidden="true"]',
    category: 'button[jsaction*="pane.rating.category"]',
    openingStatus: 'span[aria-label*="open" i], span[aria-label*="closed" i]',
};
